using System.Collections.Generic;

namespace Scramble.GameData
{
    public class NoiseTable
    {
        private static Dictionary<int, string> NoiseNames = new Dictionary<int, string>()
        {
            { 0, "Mosh Grizzly" },
            { 1, "Circle Pit Grizzly" },
            { 2, "Headbangin' Grizzly" },
            { 3, "Plague Grizzly" },
            { 4, "Decadraven" },
            { 5, "Easterraven" },
            { 6, "Nefastraven" },
            { 7, "Dixiefrog" },
            { 8, "Bigbanfrog" },
            { 9, "Funkfrog" },
            { 10, "Tradishfrog" },
            { 11, "Plague Frog" },
            { 12, "Plague Batrakos" },
            { 13, "Jelly Madchester" },
            { 14, "Jelly Swechno" },
            { 15, "Jelly Neocoustic" },
            { 16, "Jelly Germanic" },
            { 17, "Plague Jelly" },
            { 18, "Plague Nemopilema" },
            { 19, "Garage Wolf" },
            { 20, "Alterna Wolf" },
            { 21, "Grunge Wolf" },
            { 22, "Plague Wolf" },
            { 23, "House Rhino" },
            { 24, "Minimal Rhino" },
            { 25, "Dub Rhino" },
            { 26, "Swing Shark" },
            { 27, "Bebop Shark" },
            { 28, "Smooth Shark" },
            { 29, "Proto Puffer" },
            { 30, "Oi Puffer" },
            { 31, "Emo Puffer" },
            { 32, "Hardcore Puffer" },
            { 33, "Emo Puffer" },
            { 34, "Pachy R&R" },
            { 35, "Mammoth R&B" },
            { 36, "Woolly AOR" },
            { 37, "Plague Pachy" },
            { 38, "Mammoth R&B" },
            { 39, "Plague Pachy" },
            { 40, "Break Stinger" },
            { 41, "Drum 'n' Stinger" },
            { 42, "Drill 'n' Stinger" },
            { 43, "Plague Stinger" },
            { 44, "Drum 'n' Stinger" },
            { 45, "Plague Stinger" },
            { 46, "J Popguin" },
            { 47, "Electro Popguin" },
            { 48, "Brit Popguin" },
            { 49, "Distortius Rex" },
            { 50, "Phasaurus Rex" },
            { 51, "Maximizaurus Rex" },
            { 52, "Phasaurus Rex" },
            { 53, "Hardtechnoleon" },
            { 54, "Houseleon" },
            { 55, "Tropicaleon" },
            { 56, "Houseleon" },
            { 57, "Pig Samba" },
            { 58, "Pig Mazurka" },
            { 59, "Pigo Doble" },
            { 60, "Piggo Dooble" },
            { 61, "Pig Carol" },
            { 62, "Pig Cha-cha" },
            { 63, "Pig Waltz" },
            { 64, "Pig Jive" },
            { 65, "Pig Bolero" },
            { 66, "Pig Mambo" },
            { 67, "Deep Rivers Societist" },
            { 68, "Deep Rivers Societists" },
            { 69, "Pureheart" },
            { 70, "Purehearts" },
            { 71, "Variabeauty" },
            { 72, "Variabeautys" },
            { 73, "Go-go Beringei" },
            { 74, "Fuya" },
            { 75, "Susukichi" },
            { 76, "Susukichi" },
            { 77, "Mr. Mew" },
            { 78, "Mr. Mew" },
            { 79, "Grus Cantus" },
            { 80, "Iris Cantus" },
            { 81, "Leo Cantus Armo" },
            { 82, "Cervus Cantus" },
            { 83, "Motoi" },
            { 84, "Shiba" },
            { 85, "Soul Pulvis" },
            { 86, "Phoenix Cantus" },
            { 87, "Cervus Cantus α" },
            { 88, "Grus Cantus α" },
            { 89, "Iris Cantus α" },
            { 90, "Shiba α" },
            { 91, "Felidae Cantus" }
        };

    }
}
