using System.Collections.Generic;

namespace Scramble.Classes
{
    public class LanguageStrings
    {
        public Dictionary<string, string> English = new Dictionary<string, string>()
        {
            // Scramble Form
            { "{ScrambleShortTitle}", "Scramble" },
            { "{ScrambleLongTitle}", "Scramble — NEO TWEWY Save Editor" },
            { "{Language}", "Language" },
            { "{Notice}", "Notice" },
            { "{Warning}", "Warning" },
            { "{Hey}", "Hey!" },
            { "{OpenSaveFile}", "Open Save File..." },
            { "{SaveChanges}", "Save Changes" },
            { "{SaveSlots}", "Save Slots" },
            { "{Autosave}", "Autosave" },
            { "{BackupCheckbox}", "Make a backup" },
            { "{DumpSlotData}", "Dump Slot Data" },
            { "{ImportSlotData}", "Import Slot Data" },
            { "{Global}", "Global" },
            { "{SettingsEditor}", "Settings Editor" },
            { "{MiscEditor}", "Misc. Editor" },
            { "{ThisSelectedSlot}", "This selected slot" },
            { "{InitializedSlotCheckbox}", "Initialized slot" },
            { "{DateAndTimeOfSave}", "Date and time of save:" },
            { "{Difficulty}", "Difficulty:" },
            { "{Experience}", "Experience:" },
            { "{CurrentLevel}", "Current level:" },
            { "{Money}", "Money:" },
            { "{Fp:}", "FP:" },
            { "{Lv}", "Lv." },
            { "{YourParty}", "Your party" },
            { "{CharacterEditor}", "Stats Editor" },
            { "{PinsEditor}", "Pins Editor" },
            { "{ClothingEditor}", "Clothing Editor" },
            { "{SocialEditor}", "Social Tree Editor" },
            { "{CollectionEditor}", "Collection Editor" },
            { "{NoisepediaEditor}", "Noisepedia Editor" },

            {"{NoOne}", "(no one)" },
            {"{None}", "(none)" },
            {"{YesLowercase}", "yes" },
            {"{NoLowercase}", "no" },
            {"{DeckOne}", "Deck 1" },
            {"{DeckTwo}", "Deck 2" },
            {"{DeckThree}", "Deck 3" },

            { "{Items}", "Items" },
            { "{SaveId}", "Save ID" },
            { "{ItemId}", "Item ID" },
            { "{Name}", "Name" },
            { "{Type}", "Type" },
            { "{Unlocked}", "Unlocked" },
            { "{Unseen}", "Unseen" },
            { "{UnlockAll}", "(Un)lock all" },
            { "{UnseeAll}", "(Un)see all" },
            { "{UnlockSelected}", "(Un)lock selected" },
            { "{UnseeSelected}", "(Un)see selected" },

            { "{NoSelectedPin}", "(No selected pin)" },
            { "{PinInventory}", "Pin Inventory" },
            { "{AllPins}", "All Pins" },
            { "{Id}", "ID" },
            { "{PinId}", "Pin ID" },
            { "{Level}", "Level" },
            { "{Level:}", "Level" },
            { "{EXP}", "EXP" },
            { "{EXP:}", "EXP:" },
            { "{Mastered}", "Mastered" },
            { "{Amount}", "Amount" },
            { "{Amount:}", "Amount:" },
            { "{RemoveThisPin}", "Remove this pin" },
            { "{RemoveAll}", "Remove all" },
            { "{MaxLevel}", "Max level:" },
            { "{Equipped}", "Equipped:" },
            { "{MasterThisPin}", "Master this pin" },
            { "{AddPin}", "Add pin" },
            { "{x99}", "x99" },
            { "{AddEachOfEveryPin}", "Add one of each pin" },
            { "{Affinity}", "Affinity" },

            { "{WearType0}", "Headwear" },
            { "{WearType1}", "Top" },
            { "{WearType2}", "Bottom" },
            { "{WearType3}", "Shoewear" },
            { "{WearType4}", "Accessory" },
            { "{WearType5}", "Top and Bottom" },

            { "{MyClothingInventory}", "My Clothing Inventory" },
            { "{AllClothingItems}", "All Clothing" },
            { "{NoClothingSelected}", "(No clothing selected)" },
            { "{Atk:}", "ATK:" },
            { "{Def:}", "DEF:" },
            { "{Hp:}", "HP:" },
            { "{ReqStyle}", "Req. STYLE:" },
            { "{Ability:}", "ABILITY:" },
            { "{RemoveThisClothing}", "Remove this piece" },
            { "{RemoveAllClothing}", "Remove all clothing" },
            { "{AddClothing}", "Add selected" },
            { "{AddEveryClothing}", "Add one of each piece" },

            { "{StatName}", "Stat" },
            { "{BaseValue}", "Base" },
            { "{PlayerValue}", "Player-earned" },
            { "{Style:}", "STYLE:" },
            { "{+}", "+" },
            { "{MaxStats}", "Max all stats" },
            { "{AllCharacters}", "All characters" },

            { "{ShowSpoilers}", "Show spoilers" },
            { "{Spoiler}", "Spoiler" },
            { "{InYourParty}", "✔ In your party" },

            { "{SkillTreeMap}", "Social Network Map" },
            { "{CharacterInfo}", "Character Information" },
            { "{RewardSkill}", "————————— REWARD SKILL —————————" },
            { "{x}", "×" },
            { "{FP}", "FP" },
            { "{Timeframe:}", "TIMEFRAME:" },
            { "{Location:}", "LOCATION:" },
            { "{Connection}", "Connection" },
            { "{Encounter}", "Encountered" },
            { "{Skill}", "Skill" },
            { "{ConnectionEstablished}", "Established connection" },
            { "{NoSelectedCharacter}", "(No selected character)" },
            { "{FirstEntry:}", "FIRST ENTRY:" },
            { "{Connection:}", "CONNECTION:" },
            { "{Shop:}", "SHOP:" },

            { "{CaloriesEaten}", "Calories eaten:" },
            { "{Overate}", "Overate" },

            { "{DayEditor}", "Day Editor" },
            { "{ShopEditor}", "Shop Editor" },
            { "{LockStatus_U}", "UNLOCKED" },
            { "{LockStatus_L}", "LOCKED" },
            { "{LockStatus_P}", "PARTIALLY UNLOCKED" },
            { "{Hint_SkillTree_LockStatus}", "Whether this character is shown in your network tree or not\ndepends on what is the furthest you've reached in the game." },

            { "{DlcTitle}", "Unlocked DLC:" },
            { "{Dlc1_Name}", "Legendary Threads Set" },
            { "{Dlc2_Name}", "Reapers' Game Survival Set" },

            { "{Volume}", "Volume" },
            { "{MusicVol:}", "Music:" },
            { "{SfxVol:}", "Sound Effects:" },
            { "{VaVol:}", "Voices:" },
            { "{General}", "General" },
            { "{VoiceLanguage:}", "Voice Language:" },
            { "{Japanese}", "Japanese" },
            { "{English}", "English" },
            { "{Other:}", "Other:" },
            { "{ControllerVibration}", "Controller Vibration" },
            { "{DialogueAutoplay}", "Dialogue Autoplay" },
            { "{Subtitles}", "Subtitles" },

            { "{NoiseList}", "Noise List" },
            { "{#}", "#" },
            { "{Pins}", "Pins" },
            { "{NoiseInfo}", "Noise information" },
            { "{Pp:}", "PP:" },
            { "{Encountered}", "Encountered" },
            { "{RecordLevel:}", "Record level:" },
            { "{ErasedCount:}", "Erased count:" },
            { "{WeakTo:}", "Weak to:" },

            { "{ReachedDays}", "Reached days" },
            { "{CurrentDay:}", "Current day:" },
            { "{FurthestDay:}", "Furthest day:" },
            { "{ReachedDays_Warning}", "Note: For the time being, you can only change your furthest day reached." },

            { "{TrophyEditor}", "Graffiti Editor" },
            { "{TurfWarEditor}", "Turf War Editor" },
            { "{DropRate:}", "DROP RATE:" },

            { "{Points}", "Current points" },
            { "{TurfWars}", "Scramble Slams" },
            { "{CurrentPoints:}", "Current Points:" },
            { "{HighScore:}", "High Score:" },
            { "{Prizes:}", "Prizes:" },
            { "{NoParticipation}", "(didn't participate)" },
            { "{NoPlacement}", "0/3" },
            { "{OneReward}", "1/3" },
            { "{TwoRewards}", "2/3" },
            { "{ThreeRewards}", "3/3" },
            { "{MaxPoints}", "Max points" },
            { "{MaxPrizes}", "Max prizes" },
            { "{AllScrambles}", "All battles" },

            { "{AboutToMaster}", "About to master" },
            { "{UnmasterAllPins}", "(Un)master all pins" },
            { "{UnmasterSelected}", "(Un)master selected pins" },

            { "{TrophyWall}", "Graffiti Wall" },
            { "{Trophies}", "Graffiti List" },
            { "{SelectedTrophy}", "Selected graffiti" },
            { "{NoSelectedTrophy}", "No selected graffiti" },
            { "{Hint:}", "HINT:" },
            { "{Unlocked_Trophy}", "Unlocked" },
            { "{Unseen_Trophy}", "Unseen" },
            { "{X:}", "X:" },
            { "{Y:}", "Y:" },
            { "{Scale:}", "Scale:" },
            { "{RotationAngle:}", "Rotation angle:" },
            { "{UnlockAllTrophies}", "Unlock all graffiti" },
            { "{ResetPositionAll}", "Reset all positions" },
            { "{Deploy}", "(Un)deploy" },
            { "{ShowAsNew}", "Show as \"NEW\"" },
            { "{AutoDraw}", "Auto re-draw" },
            { "{RedrawWall}", "Re-draw wall" },
            { "{ExportPng}", "Export PNG" },
            { "{Z:}", "Layer:" },

            // Dialog Messages
            { "DLG_FileNotFound", "The file doesn't exist." },
            { "DLG_SaveDataAlreadyOpened", "There is a save file open already. If you didn't save changes, they will be lost." },
            { "DLG_InvalidSaveFile", "This save file is invalid. Size must be exactly 3,200,512 bytes" },
            { "DLG_BackupCheckboxNotChecked", "You didn't check the \"Make a backup\" checkbox. There's a chance the save file ends up being corrupted.\nDo you wish to continue?" },
            { "DLG_SaveDataSaved", "The changes have been successfully made to the save file." },
            { "DLG_SaveSlotDumped", "The save slot has been dumped." },
            { "DLG_BackupNotPossibleFileNotFound", "Note that I couldn't make a backup because the original file stopped existing for some reason (did you delete or move it?)" },
            { "DLG_InvalidSlotFile", "This slot file is invalid. Size must be exactly 319,952 bytes." },
            { "DLG_OverwriteSlotPrompt", "Are you sure you want to overwrite this save slot?" },
            { "DLG_DeleteAllPinsAreYouSure", "Are you sure you want to remove all pins from your inventory?" },
            { "DLG_AddAllPinsAreYouSure", "Are you sure you want to add every pin to your inventory?" },
            { "DLG_NoPinsToAddSelected", "You didn't select a pin to add." },
            { "DLG_YouCantAddMorePins", "You can't add more pins of this kind. Maximum value is 99." },
            { "DLG_ZeroPinsWarning", "Note that the game will crash if you have 0 pins.\nMake sure you add enough pins and equip them to your characters." },
            { "DLG_DeleteAllClothingAreYouSure", "Are you sure you want to remove all clothes from your inventory?" },
            { "DLG_NoClothingToAddSelected", "You didn't select a clothing piece to add." },
            { "DLG_YouCantAddMoreClothes", "You can't add more clothes. Maximum value is 9 for one piece, and 2100 in total." },
            { "DLG_NewUpdateFound", "There is a new version of Scramble. Do you want to check it out?" },
            { "DLG_NoCheckboxSelected_SkillTree", "You didn't tick any of the checkboxes. What am I supposed to (un)lock?" },
            { "DLG_ActionWillSpoil", "This action will reveal spoilers. Are you sure you want to continue?" },
            { "DLG_StartFromBeginning", "Are you sure that you want to change your current day? You will start from the beginning of that day." },
            { "DLG_FurthestDayCantBeLowerThanCurrentDay", "Your furthest day cannot be lower than your current day." }
        };

        public Dictionary<string, string> Japanese = new Dictionary<string, string>()
        {
            // Scramble Form
            { "{ScrambleShortTitle}", "Scramble" },
            { "{ScrambleLongTitle}", "Scramble — 新すばせかにセーブデータエディタ" },
            { "{Language}", "言語：" },
            { "{Notice}", "Notice" },
            { "{Warning}", "Warning" },
            { "{Hey}", "Hey!" },
            { "{OpenSaveFile}", "ファイルを開く" },
            { "{SaveChanges}", "変更内容を保存" },
            { "{SaveSlots}", "セーブスロット" },
            { "{Autosave}", "オートセーブ" },
            { "{BackupCheckbox}", "バックアップコピー" },
            { "{DumpSlotData}", "スロットをダンプ" },
            { "{ImportSlotData}", "スロットをインポート" },
            { "{Global}", "設定" },
            { "{SettingsEditor}", "設定のエディタ." },
            { "{MiscEditor}", "その他のエディタ" },
            { "{ThisSelectedSlot}", "この選択されたスロット" },
            { "{InitializedSlotCheckbox}", "ゲームが始まり" },
            { "{DateAndTimeOfSave}", "保存された日時：" },
            { "{Difficulty}", "難易度：" },
            { "{Experience}", "EXP：" },
            { "{CurrentLevel}", "現在のLVL：" },
            { "{Money}", "お金：" },
            { "{Fp:}", "CP：" },
            { "{Lv}", "LVL" },
            { "{YourParty}", "パーティー" },
            { "{CharacterEditor}", "ステータスのエディタ" },
            { "{PinsEditor}", "バッジのエディタ" },
            { "{ClothingEditor}", "ファッションのエディタ" },
            { "{SocialEditor}", "キャラボードのエディタ" },
            { "{CollectionEditor}", "コレクショのエディタ" },
            { "{NoisepediaEditor}", "エネミーのエディタ" },

            {"{NoOne}", "（誰も）" },
            {"{None}", "（なし）" },
            {"{YesLowercase}", "yes" },
            {"{NoLowercase}", "no" },
            {"{DeckOne}", "デッキ１" },
            {"{DeckTwo}", "デッキ２" },
            {"{DeckThree}", "デッキ３" },

            { "{Items}", "アイテム" },
            { "{SaveId}", "セーブID" },
            { "{ItemId}", "アイテムID" },
            { "{Name}", "項目名" },
            { "{Type}", "タイプ" },
            { "{Unlocked}", "ロック解除" },
            { "{Unseen}", "見えない" },
            { "{UnlockAll}", "すべてロック/を解除" },
            { "{UnseeAll}", "すべて見る/見えない" },
            { "{UnlockSelected}", "選択したアイテムをロック/を解除" },
            { "{UnseeSelected}", "選択したアイテムを見る/見えない" },

            { "{NoSelectedPin}", "（バッジ選択されていません）" },
            { "{PinInventory}", "バッジの在庫" },
            { "{AllPins}", "すべてのバッジ" },
            { "{Id}", "ID" },
            { "{PinId}", "バッジID" },
            { "{Level}", "レベル" },
            { "{Level:}", "レベル：" },
            { "{EXP}", "EXP" },
            { "{EXP:}", "EXP：" },
            { "{Mastered}", "MASTER" },
            { "{Amount}", "量" },
            { "{Amount:}", "量：" },
            { "{RemoveThisPin}", "このバッジの削除" },
            { "{RemoveAll}", "すべてを削除" },
            { "{MaxLevel}", "最大レベル：" },
            { "{Equipped}", "装備した：" },
            { "{MasterThisPin}", "マスターする" },
            { "{AddPin}", "バッジの追加" },
            { "{x99}", "x99" },
            { "{AddEachOfEveryPin}", "バッジの各を追加" },
            { "{Affinity}", "属性" },

            { "{WearType0}", "帽子" },
            { "{WearType1}", "トップス" },
            { "{WearType2}", "ボトム" },
            { "{WearType3}", "靴" },
            { "{WearType4}", "アクセサリー" },
            { "{WearType5}", "トップスとボトム" },

            { "{MyClothingInventory}", "衣料品の在庫" },
            { "{AllClothingItems}", "すべての服" },
            { "{NoClothingSelected}", "（服選択されていません）" },
            { "{Atk:}", "ＡＴＫ：" },
            { "{Def:}", "ＤＥＦ：" },
            { "{Hp:}", "ＨＰ：" },
            { "{ReqStyle}", "必要なＳＥＮＳＥ：" },
            { "{Ability:}", "アビリティ：" },
            { "{RemoveThisClothing}", "この服の削除" },
            { "{RemoveAllClothing}", "すべてを削除" },
            { "{AddClothing}", "服の追加" },
            { "{AddEveryClothing}", "服の各を追加" },

            { "{StatName}", "スタッツ" },
            { "{BaseValue}", "基準値" },
            { "{PlayerValue}", "プレイヤーが獲得" },
            { "{Style:}", "ＳＥＮＳＥ：" },
            { "{+}", "＋" },
            { "{MaxStats}", "９９９ステータス" },
            { "{AllCharacters}", "全キャラクター" },

            { "{ShowSpoilers}", "ネタバレ🆗" },
            { "{Spoiler}", "ネタバレ" },
            { "{InYourParty}", "パーティメンバー" },

            { "{SkillTreeMap}", "キャラクターボードのツリー表示" },
            { "{CharacterInfo}", "キャラクターの情報" },
            { "{RewardSkill}", "—————————— リワードスキル ——————————" },
            { "{x}", "×" },
            { "{FP}", "CP" },
            { "{Timeframe:}", "イベント発生タイミング：" },
            { "{Location:}", "イベント発生場所：" },
            { "{Connection}", "繋がり" },
            { "{Encounter}", "会いました" },
            { "{Skill}", "スキル" },
            { "{ConnectionEstablished}", "ネットワークが繋がりされています" },
            { "{NoSelectedCharacter}", "(キャラクター選択されていません)" },
            { "{FirstEntry:}", "最初の入力日：" },
            { "{Connection:}", "繋がりの日：" },
            { "{Shop:}", "店名：" },

            { "{CaloriesEaten}", "カロリーの食べる数：" },
            { "{Overate}", "食べすぎた" },

            { "{DayEditor}", "日のエディタ" },
            { "{ShopEditor}", "ショップのエディタ" },
            { "{LockStatus_U}", "ロック解除された" },
            { "{LockStatus_L}", "ロックされた" },
            { "{LockStatus_P}", "部分的にロック解除さた" },
            { "{Hint_SkillTree_LockStatus}", "このキャラクターをネットワークに表示するには、ゲームの初対面の日に到達している必要があります。" },

            { "{DlcTitle}", "ボーナスＤＬＣ：" },
            { "{Dlc1_Name}", "「伝説のファッションアイテムセット」" },
            { "{Dlc2_Name}", "「『死神のゲーム』生存率アップセット」" },

            { "{Volume}", "音量" },
            { "{MusicVol:}", "BGM音量：" },
            { "{SfxVol:}", "SE音量：" },
            { "{VaVol:}", "ボイス音量：" },
            { "{General}", "一般" },
            { "{VoiceLanguage:}", "音声言語:" },
            { "{Japanese}", "日本語" },
            { "{English}", "英語" },
            { "{Other:}", "他の設定：" },
            { "{ControllerVibration}", "コントローラー振動" },
            { "{DialogueAutoplay}", "ボイスイベントの自動送り" },
            { "{Subtitles}", "字幕表示" },

            { "{NoiseList}", "ノイズリスト" },
            { "{#}", "#" },
            { "{Pins}", "バッジ" },
            { "{NoiseInfo}", "ノイズの情報" },
            { "{Pp:}", "ＢＰ：" },
            { "{Encountered}", "登録された" },
            { "{RecordLevel:}", "討伐記録：" },
            { "{ErasedCount:}", "討伐数：" },
            { "{WeakTo:}", "弱点属性：" },

            { "{ReachedDays}", "ロック解除された日々" },
            { "{CurrentDay:}", "当日プレイ：" },
            { "{FurthestDay:}", "最大プレイの日：" },
            { "{ReachedDays_Warning}", "注： ゲーム内での最大到達日数は、現在の期間のみ変更できます。" },

            { "{TrophyEditor}", "グラフィティのエディタ" },
            { "{TurfWarEditor}", "スクランブルバトルのエディタ" },
            { "{DropRate:}", "DROP RATE：" },

            { "{Points}", "現在のスコア" },
            { "{TurfWars}", "スクランブルバトル" },
            { "{CurrentPoints:}", "現在のスコア：" },
            { "{HighScore:}", "ハイスコア：" },
            { "{Prizes:}", "報酬：" },
            { "{NoParticipation}", "（ないの参加）" },
            { "{NoPlacement}", "0/3" },
            { "{OneReward}", "1/3" },
            { "{TwoRewards}", "2/3" },
            { "{ThreeRewards}", "3/3" },
            { "{MaxPoints}", "最大ポイント" },
            { "{MaxPrizes}", "最大の報酬" },
            { "{AllScrambles}", "全てのバトル" },

            { "{AboutToMaster}", "マスタのすぐ下" },
            { "{UnmasterAllPins}", "すべてのバッジを（アン）マスタ" },
            { "{UnmasterSelected}", "選択したバッジを（アン）マスタ" },

            { "{TrophyWall}", "グラフィティの壁" },
            { "{Trophies}", "グラフィティのリスト" },
            { "{SelectedTrophy}", "選択したグラフィティ" },
            { "{NoSelectedTrophy}", "グラフィティが選択されていません" },
            { "{Hint:}", "ヒント：" },
            { "{Unlocked_Trophy}", "ロック解除" },
            { "{Unseen_Trophy}", "見られない" },
            { "{X:}", "Ｘ：" },
            { "{Y:}", "Ｙ：" },
            { "{Scale:}", "スケーリング：" },
            { "{RotationAngle:}", "回転角度：" },
            { "{UnlockAllTrophies}", "すべてのグラフィティのロック解除" },
            { "{ResetPositionAll}", "すべての位置をリセットします" },
            { "{Deploy}", "壁に展開します" },
            { "{ShowAsNew}", "ＮＥＷを表示" },
            { "{AutoDraw}", "オート描く" },
            { "{RedrawWall}", "壁に再描画" },
            { "{ExportPng}", "ＰＮＧ書き出し" },
            { "{Z:}", "レイヤ：" },

            // Dialog Messages
            { "DLG_FileNotFound", "ファイルが見つかりません。" },
            { "DLG_SaveDataAlreadyOpened", "すでに開いているファイルがあります。\n保存されていない変更は失われます。" },
            { "DLG_InvalidSaveFile", "セーブファイルは無効です。\nサイズは　３２００５１２バイトである必要があります。" },
            { "DLG_BackupCheckboxNotChecked", "バックアップを選択しませんでした。\nセーブファイルが破損することがあります。\n続行しますか？" },
            { "DLG_SaveDataSaved", "変更は保存されました。" },
            { "DLG_SaveSlotDumped", "セーブスロットはだんぽされました。" },
            { "DLG_BackupNotPossibleFileNotFound", "セーブファイルが削除されたため、\nバックアップが不可能です。" },
            { "DLG_InvalidSlotFile", "このスロットファイルは無効です。\nサイズは　３１９９５２バイトである必要があります。" },
            { "DLG_OverwriteSlotPrompt", "このセーブスロットを上書きしますか？" },
            { "DLG_DeleteAllPinsAreYouSure", "すべての在庫のバッジを削除しますか？" },
            { "DLG_AddAllPinsAreYouSure", "すべてのバッジを追加しますか？" },
            { "DLG_NoPinsToAddSelected", "バッジが選択されていないか。" },
            { "DLG_YouCantAddMorePins", "これ以上同じ特性を持つバッジを追加できません。\n最大値は９９。" },
            { "DLG_ZeroPinsWarning", "注：０バッジを持っている場合の結果はゲームのクラッシュ。\n必ずバッジ化も装備してください。" },
            { "DLG_DeleteAllClothingAreYouSure", "すべての在庫の服を削除しますか？" },
            { "DLG_NoClothingToAddSelected", "服が選択されていないか。" },
            { "DLG_YouCantAddMoreClothes", "これ以上同じ特性を持つ服を追加できません。\n最大値は９。合計で、最大値は２１００になります。" },
            { "DLG_NewUpdateFound", "新しいバージョンの「スクランブル」があります。 ダウンロードしますか？" },
            { "DLG_NoCheckboxSelected_SkillTree", "チェックボックスがオンになっていません。\n私は何の行動もしなかった。" },
            { "DLG_ActionWillSpoil", "この操作はネタバレを明らかにする。\n続行しますか？" },
            { "DLG_StartFromBeginning", "現在の日を変更してもよろしいですか？\nゲームはその日の初めから再開されます。" },
            { "DLG_FurthestDayCantBeLowerThanCurrentDay", "最大日数は、現在の日より前にすることはできません。" }
        };

        public Dictionary<string, string> Spanish = new Dictionary<string, string>()
        {
            // Scramble Form
            { "{ScrambleShortTitle}", "Scramble" },
            { "{ScrambleLongTitle}", "Scramble — NEO TWEWY Save Editor" },
            { "{Language}", "Idioma:" },
            { "{Notice}", "Aviso" },
            { "{Warning}", "Advertencia" },
            { "{Hey}", "Atención" },
            { "{OpenSaveFile}", "Abrir archivo..." },
            { "{SaveChanges}", "Guardar cambios" },
            { "{SaveSlots}", "Ranuras de guardado" },
            { "{Autosave}", "Autoguardado" },
            { "{BackupCheckbox}", "Hacer un respaldo" },
            { "{DumpSlotData}", "Exportar ranura" },
            { "{ImportSlotData}", "Importar ranura" },
            { "{Global}", "Global" },
            { "{SettingsEditor}", "Editar config." },
            { "{MiscEditor}", "Editar misceláneos" },
            { "{ThisSelectedSlot}", "Ranura seleccionada" },
            { "{InitializedSlotCheckbox}", "Ranura iniciada" },
            { "{DateAndTimeOfSave}", "Fecha y hora de guardado:" },
            { "{Difficulty}", "Dificultad:" },
            { "{Experience}", "Experiencia:" },
            { "{CurrentLevel}", "Nivel actual:" },
            { "{Money}", "Dinero:" },
            { "{Fp:}", "PA:" },
            { "{Lv}", "Nv." },
            { "{YourParty}", "Tu equipo" },
            { "{CharacterEditor}", "Editar stats" },
            { "{PinsEditor}", "Editar pines" },
            { "{ClothingEditor}", "Editar ropa" },
            { "{SocialEditor}", "Editar red social" },
            { "{CollectionEditor}", "Editar colecciones" },
            { "{NoisepediaEditor}", "Editar ruidopedia" },

            {"{NoOne}", "(nadie)" },
            {"{None}", "(ninguno)" },
            {"{YesLowercase}", "sí" },
            {"{NoLowercase}", "no" },
            {"{DeckOne}", "Set 1" },
            {"{DeckTwo}", "Set 2" },
            {"{DeckThree}", "Set 3" },

            { "{Items}", "Ítems" },
            { "{SaveId}", "ID del save" },
            { "{ItemId}", "ID del ítem" },
            { "{Name}", "Nombre" },
            { "{Type}", "Tipo" },
            { "{Unlocked}", "Desbloqueado" },
            { "{Unseen}", "No visto" },
            { "{UnlockAll}", "(Des)bloquear todos" },
            { "{UnseeAll}", "Olvidar/ver todos" },
            { "{UnlockSelected}", "(Des)bloquear seleccionados" },
            { "{UnseeSelected}", "Olvidar/ver seleccionados" },

            { "{NoSelectedPin}", "(Ningún pin seleccionado)" },
            { "{PinInventory}", "Mi inventario de pines" },
            { "{AllPins}", "Todos los pines" },
            { "{Id}", "ID" },
            { "{PinId}", "ID del pin" },
            { "{Level}", "Nivel" },
            { "{Level:}", "Nivel:" },
            { "{EXP}", "EXP" },
            { "{EXP:}", "EXP:" },
            { "{Mastered}", "Dominado" },
            { "{Amount}", "Cantidad" },
            { "{Amount:}", "Cantidad:" },
            { "{RemoveThisPin}", "Quitar este pin" },
            { "{RemoveAll}", "Quitar todos" },
            { "{MaxLevel}", "Nivel máx:" },
            { "{Equipped}", "Equipado:" },
            { "{MasterThisPin}", "Dominar pin" },
            { "{AddPin}", "Añadir pin" },
            { "{x99}", "x99" },
            { "{AddEachOfEveryPin}", "Añadir uno de cada pin" },
            { "{Affinity}", "Afinidad" },

            { "{WearType0}", "Cabeza" },
            { "{WearType1}", "Parte superior" },
            { "{WearType2}", "Parte inferior" },
            { "{WearType3}", "Calzado" },
            { "{WearType4}", "Accesorio" },
            { "{WearType5}", "Superior e inferior" },

            { "{MyClothingInventory}", "Mi inventario de ropa" },
            { "{AllClothingItems}", "Toda la ropa" },
            { "{NoClothingSelected}", "(Ninguna prenda seleccionada)" },
            { "{Atk:}", "ATQ:" },
            { "{Def:}", "DEF:" },
            { "{Hp:}", "PV:" },
            { "{ReqStyle}", "ESTILO requerido:" },
            { "{Ability:}", "Habilidad:" },
            { "{RemoveThisClothing}", "Quitar esta prenda" },
            { "{RemoveAllClothing}", "Quitar todas" },
            { "{AddClothing}", "Añadir prenda" },
            { "{AddEveryClothing}", "Añadir una de cada prenda" },

            { "{StatName}", "Atributo" },
            { "{BaseValue}", "Base" },
            { "{PlayerValue}", "Obtenido por el jugador" },
            { "{Style:}", "ESTILO:" },
            { "{+}", "+" },
            { "{MaxStats}", "Valores al máximo" },
            { "{AllCharacters}", "Todos los personajes" },

            { "{ShowSpoilers}", "Mostrar spoilers" },
            { "{Spoiler}", "Spoiler" },
            { "{InYourParty}", "✔ En tu equipo" },

            { "{SkillTreeMap}", "Mapa de red social" },
            { "{CharacterInfo}", "Información del personaje" },
            { "{RewardSkill}", "————————— RECOMPENSA —————————" },
            { "{x}", "×" },
            { "{FP}", "PA" },
            { "{Timeframe:}", "MARCO TEMPORAL:" },
            { "{Location:}", "LUGAR:" },
            { "{Connection}", "Conexiones" },
            { "{Encounter}", "Primer encuentro" },
            { "{Skill}", "Recompensas" },
            { "{ConnectionEstablished}", "Conexión establecida" },
            { "{NoSelectedCharacter}", "(Ningún personaje seleccionado)" },
            { "{FirstEntry:}", "PRIMER ENCUENTRO:" },
            { "{Connection:}", "CONEXIÓN:" },
            { "{Shop:}", "TIENDA:" },

            { "{CaloriesEaten}", "Calorías: " },
            { "{Overate}", "Atracados" },

            { "{DayEditor}", "Editar días" },
            { "{ShopEditor}", "Editar tiendas" },
            { "{LockStatus_U}", "DESBLOQUEADO" },
            { "{LockStatus_L}", "NO DESBLOQUEADO AÚN" },
            { "{LockStatus_P}", "DESBLOQUEADO PARCIALMENTE" },
            { "{Hint_SkillTree_LockStatus}", "Para que este personaje aparezca en tu red social, necesitas haber llegado al día de primer encuentro." },

            { "{DlcTitle}", "DLC obtenido:" },
            { "{Dlc1_Name}", "Conjunto de textiles legendarios" },
            { "{Dlc2_Name}", "Set de supervivencia del Juego de los Segadores" },

            { "{Volume}", "Volumen" },
            { "{MusicVol:}", "Música:" },
            { "{SfxVol:}", "Efectos de sonido:" },
            { "{VaVol:}", "Voces:" },
            { "{General}", "General" },
            { "{VoiceLanguage:}", "Idioma de las voces:" },
            { "{Japanese}", "Japonés" },
            { "{English}", "Inglés" },
            { "{Other:}", "Otros:" },
            { "{ControllerVibration}", "Vibración del mando" },
            { "{DialogueAutoplay}", "Autoreproducir diálogos" },
            { "{Subtitles}", "Subtítulos" },

            { "{NoiseList}", "Lista de ruido" },
            { "{#}", "#" },
            { "{Pins}", "Pines" },
            { "{NoiseInfo}", "Info. del ruido" },
            { "{Pp:}", "PP:" },
            { "{Encountered}", "Registrado" },
            { "{RecordLevel:}", "Nivel récord:" },
            { "{ErasedCount:}", "Eliminado:" },
            { "{WeakTo:}", "Débil contra:" },

            { "{ReachedDays}", "Días alcanzados" },
            { "{CurrentDay:}", "Día actual:" },
            { "{FurthestDay:}", "Máximo día alcanzado:" },
            { "{ReachedDays_Warning}", "Nota: Por el momento, solo puedes cambiar el máximo día alcanzado." },

            { "{TrophyEditor}", "Editar grafitis" },
            { "{TurfWarEditor}", "Editar Conquistas" },
            { "{DropRate:}", "TASA BOTÍN:" },

            { "{Points}", "Mis puntos" },
            { "{TurfWars}", "Conquistas cruzadas" },
            { "{CurrentPoints:}", "Puntos actuales:" },
            { "{HighScore:}", "Récord:" },
            { "{Prizes:}", "Premios:" },
            { "{NoParticipation}", "(sin participación)" },
            { "{NoPlacement}", "0/3" },
            { "{OneReward}", "1/3" },
            { "{TwoRewards}", "2/3" },
            { "{ThreeRewards}", "3/3" },
            { "{MaxPoints}", "Máx. puntos" },
            { "{MaxPrizes}", "Máx. premios" },
            { "{AllScrambles}", "Todos los Conq." },

            { "{AboutToMaster}", "A punto de dom." },
            { "{UnmasterAllPins}", "(No) dominar todos los pines" },
            { "{UnmasterSelected}", "(No) dominar los pines seleccionados" },

            { "{TrophyWall}", "Muro de grafitis" },
            { "{Trophies}", "Lista de grafitis" },
            { "{SelectedTrophy}", "Grafiti seleccionado" },
            { "{NoSelectedTrophy}", "Ningún grafiti seleccionado" },
            { "{Hint:}", "Pista:" },
            { "{Unlocked_Trophy}", "Desbloqueado" },
            { "{Unseen_Trophy}", "No visto" },
            { "{X:}", "X:" },
            { "{Y:}", "Y:" },
            { "{Scale:}", "Escala:" },
            { "{RotationAngle:}", "Ángulo de rotación:" },
            { "{UnlockAllTrophies}", "Desbloquear todos" },
            { "{ResetPositionAll}", "Restablecer posiciones" },
            { "{Deploy}", "Desplegar" },
            { "{ShowAsNew}", "Mostrar \"NUEVO\"" },
            { "{AutoDraw}", "Autodibujar" },
            { "{RedrawWall}", "Re-dibujar el muro" },
            { "{ExportPng}", "Exportar PNG" },
            { "{Z:}", "Capa:" },

            // Dialog Messages
            { "DLG_FileNotFound", "El archivo no existe." },
            { "DLG_SaveDataAlreadyOpened", "Ya hay un archivo abierto. Si no guardaste los cambios, se perderán." },
            { "DLG_InvalidSaveFile", "Este archivo no es válido. El tamaño debe ser exactamente 3.200.512 bytes" },
            { "DLG_BackupCheckboxNotChecked", "No marcaste la casilla de \"hacer un respaldo\". Es posible que el archivo guardado termine siendo corrompido.\n¿Deseas proceder?" },
            { "DLG_SaveDataSaved", "Los cambios fueron guardados con éxito." },
            { "DLG_SaveSlotDumped", "La ranura de guardado fue exportada." },
            { "DLG_BackupNotPossibleFileNotFound", "No pude hacer un respaldo porque el archivo original dejó de existir por alguna razón." },
            { "DLG_InvalidSlotFile", "Este archivo de ranura no es válido. El tamaño debe ser exactamente 319.952 bytes." },
            { "DLG_OverwriteSlotPrompt", "¿Estás segur@ de que quieres sobreescribir esta ranura?" },
            { "DLG_DeleteAllPinsAreYouSure", "¿Estás segur@ de que quieres borrar todos los pines de tu inventario?" },
            { "DLG_AddAllPinsAreYouSure", "¿Estás segur@ de que quieres agregar cada pin a tu inventario?" },
            { "DLG_NoPinsToAddSelected", "No seleccionaste ningún pin para añadir." },
            { "DLG_YouCantAddMorePins", "No puedes añadir más pines con la misma característica. El valor máximo es 99." },
            { "DLG_ZeroPinsWarning", "Toma nota que el juego crasheará si tienes 0 pines.\nAsegúrate de agregar pines suficientes y equiparlos a los personajes." },
            { "DLG_DeleteAllClothingAreYouSure", "¿Estás segur@ de que quieres quitar toda la ropa de tu inventario?" },
            { "DLG_NoClothingToAddSelected", "No seleccionaste ninguna prenda para añadir." },
            { "DLG_YouCantAddMoreClothes", "No puedes añadir más. El valor máximo es 9 para una prenda y 2100 en total." },
            { "DLG_NewUpdateFound", "Hay una nueva versión de Scramble. ¿Deseas ir a descargarla?" },
            { "DLG_NoCheckboxSelected_SkillTree", "No marcaste ninguna casilla. ¿Qué se supone que es lo que debo (des)bloquear?" },
            { "DLG_ActionWillSpoil", "Esta acción revelará spoilers. ¿Segur@ que quieres continuar?" },
            { "DLG_StartFromBeginning", "¿Estás segur@ de que quieres cambiar tu día actual? Si lo haces, empezarás desde el comienzo de ese día." },
            { "DLG_FurthestDayCantBeLowerThanCurrentDay", "Tu día máximo alcanzado no puede ser menor a tu día actual." }
        };

        public Dictionary<string, string> French = new Dictionary<string, string>()
        {
            // Scramble Form
            { "{ScrambleShortTitle}", "Scramble" },
            { "{ScrambleLongTitle}", "Scramble — NEO TWEWY Save Editor" },
            { "{Language}", "Langue:" },
            { "{Notice}", "Avis" },
            { "{Warning}", "Attention" },
            { "{Hey}", "Choisissez" },
            { "{OpenSaveFile}", "Ouvrir fichier..." },
            { "{SaveChanges}", "Enregistrer" },
            { "{SaveSlots}", "Slots de sauvegarde" },
            { "{Autosave}", "sauve automatique" },
            { "{BackupCheckbox}", "Faire une copie" },
            { "{DumpSlotData}", "Exporter slot" },
            { "{ImportSlotData}", "Importer slot" },
            { "{Global}", "Global" },
            { "{SettingsEditor}", "Éditer paramètres" },
            { "{MiscEditor}", "Éditer misc." },
            { "{ThisSelectedSlot}", "Ce slot sélectionné" },
            { "{InitializedSlotCheckbox}", "Slot commencé" },
            { "{DateAndTimeOfSave}", "Date et heure de sauvegarde :" },
            { "{Difficulty}", "Difficulté :" },
            { "{Experience}", "Experience :" },
            { "{CurrentLevel}", "Niveau actuel :" },
            { "{Money}", "Argent :" },
            { "{Fp:}", "PA :" },
            { "{Lv}", "LVL " },
            { "{YourParty}", "Ton équipe" },
            { "{CharacterEditor}", "Éditer stats" },
            { "{PinsEditor}", "Éditer badges" },
            { "{ClothingEditor}", "Éditer vêtements" },
            { "{SocialEditor}", "Éditer réseau social" },
            { "{CollectionEditor}", "Éditer collection" },
            { "{NoisepediaEditor}", "Éditer échopédie" },

            {"{NoOne}", "(personne)" },
            {"{None}", "(aucun)" },
            {"{YesLowercase}", "oui" },
            {"{NoLowercase}", "non" },
            {"{DeckOne}", "Deck 1" },
            {"{DeckTwo}", "Deck 2" },
            {"{DeckThree}", "Deck 3" },

            { "{Items}", "Objets" },
            { "{SaveId}", "ID de la save" },
            { "{ItemId}", "ID de le objet" },
            { "{Name}", "Nom" },
            { "{Type}", "Type" },
            { "{Unlocked}", "Débloqué" },
            { "{Unseen}", "Pas vu" },
            { "{UnlockAll}", "(Dé)bloquer tous" },
            { "{UnseeAll}", "Oublier/voir tous" },
            { "{UnlockSelected}", "(Dé)bloquer sélectionné" },
            { "{UnseeSelected}", "Oublier/voir sélectionné" },

            { "{NoSelectedPin}", "(Aucun badge sélectionné)" },
            { "{PinInventory}", "Mon inventaire de badges" },
            { "{AllPins}", "Tous les badges" },
            { "{Id}", "ID" },
            { "{PinId}", "ID de la badge" },
            { "{Level}", "Niveau" },
            { "{Level:}", "Niveau :" },
            { "{EXP}", "XP" },
            { "{EXP:}", "XP :" },
            { "{Mastered}", "Maîtrisé" },
            { "{Amount}", "Quantité" },
            { "{Amount:}", "Quantité :" },
            { "{RemoveThisPin}", "Supprimer ce badge" },
            { "{RemoveAll}", "Supprimer tous" },
            { "{MaxLevel}", "Niveau máx :" },
            { "{Equipped}", "Équipé par :" },
            { "{MasterThisPin}", "Maîtriser ce badge" },
            { "{AddPin}", "Ajouter ce badge" },
            { "{x99}", "x99" },
            { "{AddEachOfEveryPin}", "Ajouter un de chaque badge" },
            { "{Affinity}", "Affinité" },

            { "{WearType0}", "Couvre-chef" },
            { "{WearType1}", "Hauts" },
            { "{WearType2}", "Bas" },
            { "{WearType3}", "Calzado" },
            { "{WearType4}", "Accessoire" },
            { "{WearType5}", "Hauts et bas" },

            { "{MyClothingInventory}", "Mon inventaire de vêtements" },
            { "{AllClothingItems}", "Tous les vêtements" },
            { "{NoClothingSelected}", "(Aucun habit sélectionné)" },
            { "{Atk:}", "ATQ :" },
            { "{Def:}", "DÉF :" },
            { "{Hp:}", "PV :" },
            { "{ReqStyle}", "STYLE requis :" },
            { "{Ability:}", "Habilidad :" },
            { "{RemoveThisClothing}", "Supprimer ce vêtement" },
            { "{RemoveAllClothing}", "Supprimer tous" },
            { "{AddClothing}", "Ajouter ce vêtement" },
            { "{AddEveryClothing}", "Ajouter un de chaque vêtement" },

            { "{StatName}", "Stat" },
            { "{BaseValue}", "Base" },
            { "{PlayerValue}", "Obtenu par le joueur" },
            { "{Style:}", "STYLE :" },
            { "{+}", "+" },
            { "{MaxStats}", "Valeurs maximales" },
            { "{AllCharacters}", "Tous les personnages" },

            { "{ShowSpoilers}", "Montrer spoilers" },
            { "{Spoiler}", "Spoiler" },
            { "{InYourParty}", "✔ Dans votre équipe" },

            { "{SkillTreeMap}", "Arbre des connexions sociales" },
            { "{CharacterInfo}", "Informations de personnage" },
            { "{RewardSkill}", "————————— RÉCOMPENSE —————————" },
            { "{x}", "×" },
            { "{FP}", "PA" },
            { "{Timeframe:}", "PÉRIODE :" },
            { "{Location:}", "LIEU :" },
            { "{Connection}", "Connexions" },
            { "{Encounter}", "1ère rencontre" },
            { "{Skill}", "Récompenses" },
            { "{ConnectionEstablished}", "Connexion établie" },
            { "{NoSelectedCharacter}", "(Aucun personnage sélectionné)" },
            { "{FirstEntry:}", "1ÈRE RENCONTRE :" },
            { "{Connection:}", "CONNEXION :" },
            { "{Shop:}", "MAGASIN :" },

            { "{CaloriesEaten}", "Calories :" },
            { "{Overate}", "Suralimentée" },

            { "{DayEditor}", "Éditer jours" },
            { "{ShopEditor}", "Éditer magasins" },
            { "{LockStatus_U}", "DÉBLOQUÉ" },
            { "{LockStatus_L}", "PAS ENCORE DÉBLOQUÉ" },
            { "{LockStatus_P}", "DÉBLOQUÉ EN PARTIE" },
            { "{Hint_SkillTree_LockStatus}", "Pour que ce personnage apparaisse dans votre réseau social, vous devez avoir atteint le jour de la 1ère rencontre." },

            { "{DlcTitle}", "DLC obtenu :" },
            { "{Dlc1_Name}", "Ensemble de fringues légendaires" },
            { "{Dlc2_Name}", "Ensemble de survie pour le Jeu des Reapers" },

            { "{Volume}", "Volume" },
            { "{MusicVol:}", "Musique :" },
            { "{SfxVol:}", "Effets sonores :" },
            { "{VaVol:}", "Voix :" },
            { "{General}", "Général" },
            { "{VoiceLanguage:}", "Langue de la voix :" },
            { "{Japanese}", "Japonais" },
            { "{English}", "Anglais" },
            { "{Other:}", "Autres :" },
            { "{ControllerVibration}", "Vibrations du contrôleur" },
            { "{DialogueAutoplay}", "Dialogues auto" },
            { "{Subtitles}", "Sous-titres :" },

            { "{NoiseList}", "Liste d'Échos" },
            { "{#}", "#" },
            { "{Pins}", "Badges" },
            { "{NoiseInfo}", "Information de l'Écho" },
            { "{Pp:}", "BP :" },
            { "{Encountered}", "Rencontré" },
            { "{RecordLevel:}", "Niveau record :" },
            { "{ErasedCount:}", "Compter de effacés :" },
            { "{WeakTo:}", "Faible pour :" },

            { "{ReachedDays}", "Jours atteint" },
            { "{CurrentDay:}", "Jour en cours :" },
            { "{FurthestDay:}", "Jour maximale atteint :" },
            { "{ReachedDays_Warning}", "Note : Pour le moment, vous ne pouvez modifier que votre jour maximum atteint." },

            { "{TrophyEditor}", "Éditer graffitis" },
            { "{TurfWarEditor}", "Éditer Tabassages" },
            { "{DropRate:}", "TAUX BUTIN :" },

            { "{Points}", "Mes points" },
            { "{TurfWars}", "Les Tabassages piétons" },
            { "{CurrentPoints:}", "Points actuels :" },
            { "{HighScore:}", "Score élevé :" },
            { "{Prizes:}", "Récompenses :" },
            { "{NoParticipation}", "(n'a pas participé)" },
            { "{NoPlacement}", "0/3" },
            { "{OneReward}", "1/3" },
            { "{TwoRewards}", "2/3" },
            { "{ThreeRewards}", "3/3" },
            { "{MaxPoints}", "Max points" },
            { "{MaxPrizes}", "Max récompenses" },
            { "{AllScrambles}", "Toutes" },

            { "{AboutToMaster}", "Sur le point" },
            { "{UnmasterAllPins}", "(Pas) maîtriser tous les badges" },
            { "{UnmasterSelected}", "(Pas) maîtriser les badges sélectionnés" },

            { "{TrophyWall}", "Mur de graffitis" },
            { "{Trophies}", "Liste des graffitis" },
            { "{SelectedTrophy}", "Graffiti sélectionné" },
            { "{NoSelectedTrophy}", "Aucun graffiti sélectionné" },
            { "{Hint:}", "Indice :" },
            { "{Unlocked_Trophy}", "Débloqué" },
            { "{Unseen_Trophy}", "Pas encore vu" },
            { "{X:}", "X :" },
            { "{Y:}", "Y :" },
            { "{Scale:}", "Mise à l'échelle :" },
            { "{RotationAngle:}", "Angle de rotation :" },
            { "{UnlockAllTrophies}", "Débloquer toutes les graffitis" },
            { "{ResetPositionAll}", "Réinitialiser positions" },
            { "{Deploy}", "Déployer" },
            { "{ShowAsNew}", "Afficher \"NOUVEAU\"" },
            { "{AutoDraw}", "Dessin automatique" },
            { "{RedrawWall}", "Redessiner le mur" },
            { "{ExportPng}", "Exporter PNG" },
            { "{Z:}", "Calque :" },

            // Dialog messages
            { "DLG_FileNotFound", "Le fichier de sauvegarde n'existe pas." },
            { "DLG_SaveDataAlreadyOpened", "Il y a déjà un fichier ouvert. Si vous n'avez pas enregistré vos modifications, elles seront perdues." },
            { "DLG_InvalidSaveFile", "Ce fichier n'est pas valide. La taille doit être exactement de 3 200 512 octets." },
            { "DLG_BackupCheckboxNotChecked", "Vous n'avez pas coché la case \"faire une sauvegarde\". Le fichier enregistré peut finir par être corrompu.\nVoulez-vous toujours continuer ?" },
            { "DLG_SaveDataSaved", "Les modifications ont été enregistrées avec succès." },
            { "DLG_SaveSlotDumped", "La slot de sauvegarde a été exporté" },
            { "DLG_BackupNotPossibleFileNotFound", "Je n'ai pas pu faire de sauvegarde car le fichier d'origine a cessé d'exister pour une raison quelconque." },
            { "DLG_InvalidSlotFile", "Ce fichier de slot n'est pas valide. La taille doit être exactement de 319 952 octets" },
            { "DLG_OverwriteSlotPrompt", "Voulez-vous vraiment écraser cet slot ?" },
            { "DLG_DeleteAllPinsAreYouSure", "Êtes-vous sûr de vouloir supprimer toutes les badges de votre inventaire ?" },
            { "DLG_AddAllPinsAreYouSure", "Êtes-vous sûr de vouloir supprimer toutes les badges de votre inventaire ?" },
            { "DLG_NoPinsToAddSelected", "Vous n'avez sélectionné aucune badge à ajouter." },
            { "DLG_YouCantAddMorePins", "Vous ne pouvez pas ajouter plus de badges avec la même caractéristique. La valeur maximale est 99." },
            { "DLG_ZeroPinsWarning", "Prenez note que le jeu plantera si vous avez 0 badges.\nAssurez-vous d'ajouter suffisamment de badges et de les équiper des personnages." },
            { "DLG_DeleteAllClothingAreYouSure", "Êtes-vous sûr de vouloir supprimer tous les vêtements de votre inventaire ?" },
            { "DLG_NoClothingToAddSelected", "Vous n'avez sélectionné aucun vêtement à ajouter." },
            { "DLG_YouCantAddMoreClothes", "Vous ne pouvez pas ajouter plus de ce vêtement. La valeur maximale est 9 pour une pièce et 2100 au total." },
            { "DLG_NewUpdateFound", "Il existe une nouvelle version de Scramble. Voulez-vous aller le télécharger ?" },
            { "DLG_NoCheckboxSelected_SkillTree", "Vous n'avez coché aucune des cases. Que dois-je (dé)bloquer ?" },
            { "DLG_ActionWillSpoil", "Cette action révélera spoilers. Souhaitez-vous continuer malgré tout ?" },
            { "DLG_StartFromBeginning", "Êtes-vous sûr de vouloir changer votre journée actuelle ? Vous commencerez dès le début de cette journée." },
            { "DLG_FurthestDayCantBeLowerThanCurrentDay", "Votre jour maximum atteint ne peut pas être inférieur à votre jour en cours." }
        };

        public Dictionary<string, string> Italian = new Dictionary<string, string>();

        public Dictionary<string, string> German = new Dictionary<string, string>();

        public string GetLanguageString(byte Language, string Key)
        {
            switch (Language)
            {
                case 0:
                default:
                    if (English.ContainsKey(Key))
                    {
                        return English[Key];
                    }
                    return Key;

                case 1:
                    if (Japanese.ContainsKey(Key))
                    {
                        return Japanese[Key];
                    }
                    return GetLanguageString(0, Key);

                case 2:
                    if (Spanish.ContainsKey(Key))
                    {
                        return Spanish[Key];
                    }
                    return GetLanguageString(0, Key);

                case 3:
                    if (French.ContainsKey(Key))
                    {
                        return French[Key];
                    }
                    return GetLanguageString(0, Key);

                case 4:
                    if (Italian.ContainsKey(Key))
                    {
                        return Italian[Key];
                    }
                    return GetLanguageString(0, Key);

                case 5:
                    if (German.ContainsKey(Key))
                    {
                        return German[Key];
                    }
                    return GetLanguageString(0, Key);
            }
        }
    }
}
